apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-03-26T06:23:40Z
  generation: 1
  labels:
    run: go-ok
  name: go-ok
  namespace: default
  resourceVersion: "704743"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/go-ok
  uid: 398c3230-30be-11e8-ac8c-08002716e8d2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-ok
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: go-ok
    spec:
      containers:
      - image: cjimti/go-ok
        imagePullPolicy: Always
        name: go-ok
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-26T06:23:40Z
    lastUpdateTime: 2018-03-26T06:23:40Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1